//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
@interface ContactInfoViewController : UIViewController

- (void)ContactsViewReloadData;
- (unsigned long)GetFromScene;
- (void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
- (void)OnSelectSession:(id)arg1 SessionSelectController:(id)arg2;
- (void)OnSelectSessionCancel:(id)arg1;
- (void)OnUpdateCertInfo;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)bindFacebookReturn;
- (void)bindPhoneReturn;
- (void)canNotFollowContact:(id)arg1;
- (void)confirmExpose:(unsigned long)arg1;
- (void)contactVerifyOk:(id)arg1;
- (void)copyContactField:(id)arg1 toContact:(id)arg2;
- (void)dealloc;
- (void)delAllMsg;
- (void)doReset;
- (id)getContactVerifyLogic;
- (id)getMyFriendContact;
- (id)getShareMyFriendParentViewController;
- (id)getUserData;
- (id)getViewController;
- (void)goToBindQQ;
- (BOOL)hadAddContact;
- (void)handleSelectedBindPhoneCell;
- (void)handleSelectedPrivateContactListCell;
- (id)init;
- (void)initSystemPluginData:(int)arg1;
- (id)initWithTitle:(id)arg1;
- (BOOL)isFromBlackList;
- (BOOL)isFromChatroomInfo;
- (BOOL)isFromChatroomVerify;
- (BOOL)isFromFriendAssist;
- (BOOL)isFromNotifyMessage;
- (BOOL)isFromWCProfile;
- (BOOL)isInMyContactList;
- (BOOL)isMyQQEmailInfo;
- (BOOL)isNeedHideUserName;
- (BOOL)isNeedVerify;
- (BOOL)isQQContact;
- (BOOL)isWeiboContact;
- (void)jumpToContentViewController:(id)arg1;
- (void)onAddToContact;
- (void)onDeleteContact:(id)arg1;
- (void)onEditRemarkName;
- (void)onExpose;
- (void)onExposeByRecommand;
- (void)onExposeFriend;
- (BOOL)onFilterSendReceiver:(id)arg1;
- (void)onFinishedShareMyFriend:(BOOL)arg1;
- (void)onFriendRequestSend;
- (void)onGoToContentViewController:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)onNewMessage:(id)arg1;
- (void)onPopToRootViewController:(BOOL)arg1;
- (void)onPopViewController:(BOOL)arg1;
- (void)onPresentViewController:(id)arg1;
- (void)onProfileChange;
- (void)onPushViewController:(id)arg1;
- (void)onRemoveContact;
- (void)onSayHello;
- (void)onSayHelloViewSendSayHello:(id)arg1;
- (void)onSendVerifyMsg;
- (void)onSetStrangerDesc:(id)arg1;
- (void)onSetStrangerRemark:(id)arg1;
- (void)onSetWCPermissions;
- (void)onSetWCStrangerPermissions;
- (void)onShareMyFriend;
- (void)onStrangerContactUpdated:(id)arg1;
- (void)onTalk:(id)arg1;
- (void)onVerifyOK;
- (void)onVerifyOKWithContact:(id)arg1;
- (void)onWCGroupModMemberReturn:(BOOL)arg1 group:(id)arg2;
- (void)reloadContactAssist;
- (void)reloadData;
- (void)reloadFloatView;
- (void)reloadView;
- (void)setHadAddContact;
- (void)showAlbumList;
- (void)showFolderConfigPage;
- (void)startLoadingWithText:(id)arg1;
- (void)statBanner;
- (void)stopLoadingWithFailText:(id)arg1;
- (void)stopLoadingWithOKText:(id)arg1;
- (id)tagForActivePage;
- (void)updateContactFromServer;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillLayoutSubviews;


- (void)onSetStrangerRemark:(id)arg1;
@end

