//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface WCListView : UIView

- (id)FindTheRowViewContainDataItem:(id)arg1;
- (void)MMImagePickerManager:(id)arg1 didFinishPickingImageWithInfo:(id)arg2;
- (void)MMImagePickerManagerDidCancel:(id)arg1;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)animationDidEndRemainView:(id)arg1 hintDataItem:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)clearAnimationProperties;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (id)genImageView:(id)arg1 imageType:(int)arg2;
- (id)getImageViewByDataItem:(id)arg1;
- (id)getViewController;
- (void)handleClickImageView:(id)arg1;
- (void)handleFeedView:(id)arg1;
- (void)handleMusicView:(id)arg1;
- (void)handleTextView:(id)arg1;
- (void)handleVideoView:(id)arg1;
- (id)idForIndexPath:(id)arg1;
- (int)indexOfPageForMediaItem:(id)arg1;
- (void)initFooterView;
- (void)initHeaderView;
- (void)initTableView;
- (void)initTipsLabel;
- (id)initWithData:(id)arg1 frame:(struct CGRect)arg2 contact:(id)arg3;
- (void)jumpToContentViewController:(id)arg1;
- (void)layoutSubviews;

- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onClickWCImage:(id)arg1;
- (void)onClickWCPuzzleImage:(id)arg1;
- (void)onCloseIntroView;
- (void)onDataChanged:(id)arg1;
- (void)onDeleteData;
- (void)onIKnowItBtnClick;
- (void)onNoMoreDataWithRet:(int)arg1;
- (void)onRestartUpload;
- (void)onTopBarFrameChanged;
- (void)openCommitViewController:(BOOL)arg1 arrImage:(id)arg2;
- (void)refreshFooterEnd:(unsigned long)arg1;
- (void)refreshHeaderEnd:(unsigned long)arg1;
- (void)reloadBackGround;
- (void)scrollTableViewToShowDataItem:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;

- (void)shouldReloadData:(id)arg1;
- (void)showAnimationToImageView;
- (void)showContactInfo;
- (void)showDetailView:(id)arg1;
- (void)showDetailViewController:(id)arg1;
- (void)showImagePicker:(int)arg1;
- (void)showNoContentTips:(BOOL)arg1;
- (void)showPhotoAlert:(id)arg1;
- (void)showUploadOption:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)touchesBegan_TableView:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled_TableView:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded_TableView:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved_TableView:(id)arg1 withEvent:(id)arg2;
- (void)updateRowsData;



@end

