//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import "CBaseContactInfoAssist.h"

@interface WeixinContactInfoAssist : CBaseContactInfoAssist

- (void)AddNewActionSheetCell2Array:(id)arg1 WithText:(id)arg2 WithImage:(id)arg3;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)actionSheet:(id)arg1 didSelectWithItem:(id)arg2;
- (void)addToBlackList:(id)arg1;
- (void)contactVerifyOk:(id)arg1 opCode:(unsigned long)arg2;
- (void)dealloc;
- (void)doAddToBlackList;
- (void)doDeleteContact;
- (id)getInfoDisplayName;
- (void)handleAddedContact;
- (id)init;
- (void)initAddContactBtn;
- (void)initBlackAndExposeContactBtn;
- (void)initBlackListTipsLabel;
- (void)initDeleteBtn;
- (void)initDeleteHead;
- (void)initExposeBtn;
- (void)initFooterBtnArea;
- (void)initFooterView;
- (void)initHeaderView;
- (void)initHelloWord;
- (void)initSayHelloBtn;
- (void)initSendMsgBtn;
- (void)initVerifyBtn;
- (BOOL)initVoiceVoip;
- (BOOL)initVoipBtn;
- (void)initWCPrivacyButton;
- (BOOL)isNeedShowRightBtn;
- (BOOL)isShowBlackAction;
- (BOOL)isShowExposeButton;
- (void)onAction;
- (void)onNewMessage:(id)arg1;
- (void)onOpenVoiceVoipView;
- (void)onOpenVoipActionSheet:(id)arg1;
- (void)onOpenVoipView;
- (void)onRelpyContact:(id)arg1;
- (void)onStartChat:(id)arg1;
- (void)onVerifyContact:(id)arg1 opcode:(unsigned long)arg2;
- (void)onVerifyContactOk;
- (void)opBlackList:(id)arg1;
- (void)opDelete:(id)arg1;
- (void)opExpose;
- (void)reloadTableView;
- (void)removeFromBlackList;
- (void)showRightButton;
- (void)updateCurrentFooterBtnOffsetX:(float)arg1;
- (void)updateFooterView;
- (void)updateRemarkLabel;
- (void)updateSaveRemarkNameBtn;
- (void)updateToBigSendMsgBtn;

@end

