//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import <UIKit/UIKit.h>

@interface MoreViewController : UIViewController

- (void)showChangeLanguage;
- (void)showEmoticonStoreView;
- (void)showFavoriteView;
- (void)showHtml5PayView;
- (void)showKitchen;
- (void)showMyQRCodeInProfileView;
- (void)showMyWCView;
- (void)showPrivateSetting;
- (void)showProfileView;
- (void)showSettingView;
- (void)showWCCardView;
- (void)showWCPayView;

@end

