//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface CContact : CBaseContact
    
    

- (_Bool)IsAddFromLbs;
- (_Bool)IsAddFromShake;
- (_Bool)IsUserInChatRoom:(id)arg1;
- (_Bool)copyFieldFromContact:(id)arg1;
- (_Bool)copyPatialFieldFromContact:(id)arg1;
- (_Bool)hasMatchHashPhone;
- (_Bool)isAccountDeleted;
- (_Bool)isAdmin;
- (_Bool)isBrandContact;
- (_Bool)isChatStatusNotifyOpen;
- (_Bool)isContactFrozen;
- (_Bool)isContactSessionTop;
- (_Bool)isContactTypeShouldDelete;
- (_Bool)isHasMobile;
- (_Bool)isHasWeiDian;
- (_Bool)isHolderContact;
- (_Bool)isIgnoreBrandContat;
- (_Bool)isLocalizedContact;
- (_Bool)isMyContact;
- (_Bool)isShowChatRoomDisplayName;
- (_Bool)isShowLinkedIn;
- (_Bool)isVerified;
- (_Bool)isVerifiedBrandContact;

@end

