//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface SayHelloViewController : UIViewController

+ (void)OnViewDetail:(id)arg1 prarentViewController:(id)arg2;
+ (void)makeHelloCell:(id)arg1 helloMsg:(id)arg2 delegate:(id)arg3;

- (id)GetClearTip;
- (void)OnClear:(id)arg1;
- (void)OnReturn;
- (void)OnSayHelloDataChange;
- (void)OnSayHelloDataSendVerifyMsg:(id)arg1;
- (void)OnSayHelloDataVerifyContactOK:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)addGoogleFriend;
- (void)addMobileFriend;
- (void)addQQFriend;
- (void)bindPhoneReturn;
- (void)dealloc;
- (id)getViewController;
- (void)initData;
- (void)initTableView;
- (void)initView;

- (id)makeNearByHeaderView;
- (id)makeNewFriendHeaderView;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onAddContact;
- (void)onClearMyLbsDataFinishedWithResult:(BOOL)arg1;
- (void)onClearNearHeaderClicked:(id)arg1;
- (void)onContactsItemViewRightButtonClick:(id)arg1;
- (BOOL)shouldShowNearByHeaderView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)updateHeaderView;
- (void)updateNoHello;
- (void)verifyContactWithOpCode:(id)arg1 opcode:(unsigned long)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)willAppear;



@end

