//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface CContact : NSObject

- (_Bool)IsAddFromLbs;
- (_Bool)IsAddFromShake;
- (_Bool)IsUserInChatRoom:(id)arg1;
- (long long)compareForFavourGroup:(id)arg1;
- (_Bool)copyFieldFromContact:(id)arg1;
- (_Bool)copyPatialFieldFromContact:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)externalInfoJSONCache;
- (_Bool)genContactFromShareCardMsgWrap:(id)arg1;
- (void)genContactFromShareCardMsgWrapContent:(id)arg1;
- (id)getChatRoomMemberDisplayName:(id)arg1;
- (id)getChatRoomMemberNickName:(id)arg1;
- (id)getChatRoomMembrGroupNickName:(id)arg1;
- (id)getLabelIDList;
- (id)getMobileDisplayName;
- (id)getMobileList;
- (id)getMobileNumString;
- (id)getNewChatroomData;
- (id)getNormalContactDisplayDesc;
- (id)getValueTypeTable;
- (_Bool)hasMatchHashPhone;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithModContact:(id)arg1;
- (id)initWithShareCardMsgWrap:(id)arg1;
- (id)initWithShareCardMsgWrapContent:(id)arg1;
- (_Bool)isAccountDeleted;
- (_Bool)isAdmin;
- (_Bool)isBrandContact;
- (_Bool)isChatStatusNotifyOpen;
- (_Bool)isContactFrozen;
- (_Bool)isContactSessionTop;
- (_Bool)isContactTypeShouldDelete;
- (_Bool)isHasMobile;
- (_Bool)isHasWeiDian;
- (_Bool)isHolderContact;
- (_Bool)isIgnoreBrandContat;
- (_Bool)isLocalizedContact;
- (_Bool)isMyContact;
- (_Bool)isShowChatRoomDisplayName;
- (_Bool)isShowLinkedIn;
- (_Bool)isVerified;
- (_Bool)isVerifiedBrandContact;
- (_Bool)needShowUnreadCountOnSession;
- (void)setChatRoomDataWithoutEmojiChange:(id)arg1;
- (void)setChatStatusNotifyOpen:(_Bool)arg1;
- (void)setExternalInfoJSONCache:(id)arg1;
- (void)setSignatureWithoutEmojiChange:(id)arg1;
- (void)tryLoadExtInfo;
- (id)xmlForMessageWrapContent;


@end

