//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface ContactsViewController : UIViewController

- (int)ConvertToNormalContactSection:(int)arg1;
- (BOOL)HasBindPhoneTip;
- (BOOL)HasBrandGroup;
- (BOOL)HasEnterpriseBrandGroup;
- (BOOL)HasHelloGroup;
- (BOOL)HasNewUserTip;
- (void)MMVoiceSearchBar:(id)arg1 textDidChange:(id)arg2;
- (void)MMVoiceSearchBarCancelButtonClicked:(id)arg1;
- (void)MMVoiceSearchBarSearchButtonClicked:(id)arg1;
- (BOOL)MMVoiceSearchBarShouldBeginEditing:(id)arg1;
- (void)OnSayHelloDataChange;
- (void)OnVoiceSearchButtonDown;
- (void)SearchBarBecomeActive;
- (void)SearchBarBecomeUnActive;
- (void)addBlurEffectView;
- (void)addRedDotInGroupCell:(id)arg1 existNewBrand:(BOOL)arg2;
- (void)bindPhoneReturn;
- (void)cancelSearch;
- (void)dealloc;
- (void)didAppear;
- (void)didReceiveMemoryWarning;
- (void)displayControllerSetActive:(BOOL)arg1 animated:(BOOL)arg2;
- (void)doSearch:(id)arg1 Pre:(BOOL)arg2;
- (void)finishSearchBarImmediately;
- (float)getMainTableBottomInset;
- (unsigned long)getSectionType:(int)arg1;
- (id)getVCWithDeepLinkName:(id)arg1;
- (id)getViewController;
- (void)handleSelectEnterpriseBrand:(unsigned int)arg1;
- (void)handleSelectdBindPhone;
- (void)handleSelectdBrandGroup:(int)arg1;
- (void)handleSelectdChatRoom;
- (void)handleSelectdContactTag;
- (void)handleSelectdHelloGroup;
- (void)handleSelectdHelloGroup:(unsigned int)arg1;
- (void)handleSelectdNewUserTip;
- (BOOL)hasShowSearchBar;
- (void)hideSearchBar;
- (id)init;
- (void)initBarItem;
- (void)initCountLabel:(id)arg1;
- (void)initData;
- (void)initDeepLinkConfig;
- (void)initSearchBar;
- (void)initTableView;
- (void)initTitleArea;
- (void)initView;

- (void)makeBindPhoneCell:(id)arg1;
- (void)makeCell:(id)arg1 contact:(id)arg2;
- (void)makeCell:(id)arg1 tableCell:(id)arg2 section:(unsigned int)arg3 row:(unsigned int)arg4;
- (void)makeChatRoomCell:(id)arg1;
- (void)makeContactTagCell:(id)arg1;
- (void)makeEnterpriseBrandCell:(id)arg1 row:(int)arg2;
- (void)makeGroupCell:(id)arg1 head:(id)arg2 title:(id)arg3;
- (void)makeHelloGroupCell:(id)arg1;
- (void)makeHelloGroupCelll:(id)arg1 row:(unsigned int)arg2;
- (void)makeNewUserTipCell:(id)arg1;
- (int)numberOfCellForBrandGroup;
- (int)numberOfCellForEnterpriseBrandGroup;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onAddContact;
- (void)onBrandServiceAddedNewItem;
- (void)onContactsDataChange;
- (BOOL)onFilterContactCandidate:(id)arg1;
- (void)onFriendAssistUnreadCountChanged;
- (void)openContactInfoView:(int)arg1;
- (void)reLayoutSubviews;
- (void)resetTableViewOffset:(id)arg1;
- (void)resetViewStatus;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (void)setSearchTableResultText:(id)arg1;
- (BOOL)shouldShowTabbar;
- (void)showContactInfoView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)updateCount;
- (void)updateEnterpriseBrandItemCell:(id)arg1 contact:(id)arg2;
- (void)updateHelloGroup;
- (void)updateNewContactsItemCell:(id)arg1 contact:(id)arg2;
- (void)updateTabBarBadge;
- (void)updateViewWhenSelectTab:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillPush:(BOOL)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willAppear;
- (void)willDisshow;
- (void)willShow;

@end

