 //
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WWKAttendanceCheckViewController : UITableViewController


- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2 updatingLocation:(_Bool)arg3;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (void)wwKAttendationBinaryLocationCell2DidClickReload;
- (void)multiImageBrowseViewControllerWillBack;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)sendImg:(id)arg1;
- (void)didFinishPickPhotos:(id)arg1 isSendOriginalSize:(_Bool)arg2;
- (void)wwkAttendationBinaryCheckCellViewDidCheck;
- (void)wwkAttendationRandomCheckCellViewDidCheck;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)wwkConversationLBSViewController:(id)arg1 DidSelectLocation:(id)arg2;
- (void)wwkAttendationRandomCheckImageInfoCellViewDidClickAddImageButton;
- (void)wwkAttendationCheckInfoCellViewDidClickMap;
- (void)wwkAttendationRandomCheckImageInfoCellViewDidClickImageButtonAtIndex:(unsigned long long)arg1;
- (void)attendanceReportReasonControllerDidCancel;
- (void)attendancePopDidClickReportDetail:(id)arg1;
- (void)attendancePopDidClickComfirm:(id)arg1;
- (id)p_getBinaryCheckCell;
- (void)p_updateUI;
- (void)p_updateUIWithMangeInfo;
- (void)p_segmentDidChange;
- (void)p_clearData;
- (void)p_onDidClickedRightItem;
- (void)p_showAlertWithSuccess:(_Bool)arg1 tips:(id)arg2;
- (void)p_makeCheckWithCheckType:(int)arg1 isFromReportReason:(_Bool)arg2 andReportReasonNote:(id)arg3 isFromConfirmCheckin:(_Bool)arg4 timeLineID:(unsigned int)arg5;
- (void)p_autoCheckBinaryLocationException:(struct CLLocationCoordinate2D)arg1;
- (void)p_mannulCheckBinaryException:(int)arg1 withTimeLineID:(unsigned int)arg2;
- (unsigned long long)p_todayRandomCount;
- (void)p_showLocationPermissionClosedAlert;
- (void)p_showNetworkNotAvailableAlert;
- (void)p_onTimeRefreshTimerReached;
- (void)p_onLocationRefreshTimerReached;
- (void)p_onAppDidBecomeActive;
- (void)onPvMergeWillOpen:(id)arg1;
- (id)p_checkStatusHintTextAndCheckButtonEnable;
- (unsigned int)p_offWorkSecWithTimeLineID:(unsigned int)arg1;
- (unsigned int)p_nextTimeLineIDWithTimeLineID:(unsigned int)arg1;
- (unsigned int)p_nextTimeLineWorkSecWithTimeLineID:(unsigned int)arg1;
- (unsigned int)p_workSecWithTimeLineID:(unsigned int)arg1;
- (id)p_checkStatusHintTextAndCheckButtonEnableV12:(_Bool)arg1;
- (void)p_sortAttendanceRecordByTime;
- (void)p_startMapViewLocation;
- (void)p_stopMapViewLocation;
- (void)p_updateMapViewLocation;
- (void)p_updateUserLocation;
- (void)p_onTapTimeLabel:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;
- (id)initWithCheckType:(int)arg1 andFromType:(long long)arg2;



@end

