//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@interface ARERealityViewController : UIViewController
- (void)back;
- (void)cameraView:(id)arg1 didFindObject:(id)arg2;
- (void)cameraViewAnimateClicked:(id)arg1;
- (void)cameraViewAnimateEnd:(id)arg1;
- (void)cameraViewDidFinishLoading:(id)arg1;
- (void)checkCameraAndEnvelopeReady;
- (void)confirmExit;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)doExit;
- (void)envelopeDidFound;
- (void)envelopeDidOpenSuccess:(id)arg1;
- (void)envelopeInspectByEdgeSdk;
- (void)envelopeTouched;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)initWithCrowd:(id)arg1 sign:(id)arg2 annotation:(id)arg3 userLocation:(id)arg4;
- (_Bool)isEnvelopeFound;
- (_Bool)isEnvelopeLoaded;
- (void)loadView;
- (void)manager:(id)arg1 resultType:(unsigned long long)arg2 combineResult:(id)arg3 error:(id)arg4;
- (void)navRightBarButtonItem;
- (void)notifyMapRecievedEnvelope:(id)arg1;
- (void)onTorch;
- (void)openCombineLuckMoneyViaPicCloudId:(id)arg1;
- (void)presentFailedAlertViewWithTitle:(id)arg1 withBizNo:(id)arg2 withExit:(_Bool)arg3 withNotify:(_Bool)arg4;
- (void)queryEnvelopeDetailInfo;
- (void)setupViews;
- (void)showAskTips;
- (void)showPopMenu;
- (void)showProfile;
- (void)toggleRealityFlashLight:(id)arg1;
- (void)touchedUpPreviewButton:(id)arg1;
- (void)updateEnvelopeElements;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDestroy;
- (void)viewWillDisappear:(_Bool)arg1;


@end

