//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WCBaseControlLogic : NSObject


- (void)addTopViewController:(id)arg1;
- (void)cancel;
- (void)checkStopLogic;
- (void)dismissCurrentViewAndCheckStopLogicWithAnimated:(_Bool)arg1;
- (void)dismissCurrentViewWithAnimated:(_Bool)arg1;
- (id)getCurrentViewController;
- (void)gotoRootViewControllerAndStopLogicWithAnimated:(_Bool)arg1;
- (void)gotoRootViewControllerWithAnimated:(_Bool)arg1;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2 Animation:(_Bool)arg3;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2 Present:(_Bool)arg3;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2 Present:(_Bool)arg3 Animation:(_Bool)arg4;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2 Present:(_Bool)arg3 showNavigation:(_Bool)arg4 Animation:(_Bool)arg5;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2 Present:(_Bool)arg3 showNavigation:(_Bool)arg4 Animation:(_Bool)arg5 transitioningDelegate:(id)arg6;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2 Title:(id)arg3 HeadTip:(id)arg4;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2 Title:(id)arg3 HeadTip:(id)arg4 Present:(_Bool)arg5;
- (id)gotoViewController:(Class)arg1 withData:(id)arg2 Title:(id)arg3 HeadTip:(id)arg4 Present:(_Bool)arg5 Animation:(_Bool)arg6;
- (id)gotoViewControllerHideNavigation:(Class)arg1 withData:(id)arg2 Animation:(_Bool)arg3;
- (id)init;
- (_Bool)isLogicCancel;
- (_Bool)isLogicCompleteOK;

- (_Bool)onError:(id)arg1;
- (void)pause;
- (void)presentViewController:(id)arg1 Animated:(_Bool)arg2 showNavigation:(_Bool)arg3;
- (void)presentViewController:(id)arg1 Animated:(_Bool)arg2 showNavigation:(_Bool)arg3 transitioningDelegate:(id)arg4;
- (void)pushViewController:(id)arg1 Animated:(_Bool)arg2;
- (void)pushViewController:(id)arg1 Animated:(_Bool)arg2 transitioningDelegate:(id)arg3;
- (void)removeTopViewController;
- (void)resume;
- (void)setRootViewControllerDelegate:(id)arg1;
- (void)setlogicDelegate:(id)arg1;
- (void)showLoadingOK:(id)arg1;
- (void)startLoading;
- (void)startLoadingWithTip:(id)arg1;
- (void)startLogic;
- (void)stopLoading;
- (void)stopLogic;



@end

