//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
@interface SayHelloDataLogic : NSObject


+ (id)getContactFrom:(id)arg1;


- (void)clearMsg:(unsigned int)arg1;
- (void)clearMsg:(unsigned int)arg1 ForIndex:(unsigned int)arg2;
- (void)contactVerifyOk:(id)arg1 opCode:(unsigned int)arg2;
- (void)dealloc;
- (id)getChatName:(unsigned int)arg1;
- (id)getContactForIndex:(unsigned int)arg1;
- (id)getContactForUserName:(id)arg1;
- (unsigned int)getHelloCount; //获取cell个数
- (void)handleAddedContact:(id)arg1;
- (id)initWithScene:(unsigned int)arg1 delegate:(id)arg2;
- (void)loadData:(unsigned int)arg1;

- (void)onContactVerifyFail;
- (void)onContactVerifyFillVerifyMsg:(id)arg1;
- (void)onFriendAssistAddMsg:(id)arg1;
- (void)onFriendAssistClearMsg:(id)arg1;
- (void)onFriendAssistRelpyMsg:(id)arg1;
- (void)onFriendAssistStatusChange:(id)arg1;
- (void)onFriendAssistUnreadCountChanged;
- (void)onModifyContact:(id)arg1;
- (void)onSetStrangerRemark:(id)arg1;
- (void)removeArrHello:(id)arg1;


@end

