//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface MMImagePickerController : UIViewController

- (void)MMImagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)MMImagePickerControllerDidCancel:(id)arg1;
- (void)cancelImagePicker;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (int)getPickerScene;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)increasePreviewCount;
- (void)removeImageDatas;
- (void)reportPreviewCount;
- (void)selectedAssets:(id)arg1;
- (void)selectedGif:(id)arg1;
- (void)selectedVideo:(id)arg1;

@end

