//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface WCNewCommitViewController : UIViewController


- (void)OnDone;
- (void)OnFacebookBinded;
- (void)OnPostTimeline;
- (void)OnReturn;
- (void)adjustSubviewRects;
- (void)afterProcessSingleImage;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;

- (void)bindFacebook;
- (void)bindQQ;
- (void)cancelIcloudActivity;
- (_Bool)checkImageState;
- (void)commonInit;
- (_Bool)couldSelectContacts;
- (void)createSubviews;
- (void)dealloc;

- (void)doExit;
- (void)facebookCheckAccessTokenValidFinished:(_Bool)arg1;
- (void)fbDidLogin;
- (void)fbDidNotLogin;
- (id)getShowAddress;
- (id)getViewController;
- (void)hideInputController;
- (void)imagesUpdated;
- (id)init;
- (void)initView;
- (id)initWithImages:(id)arg1 contacts:(id)arg2;

- (void)onFacebookClicked:(id)arg1;
- (void)onLocationCellClicked; // 所在位置
- (void)onPOIPickerFinished:(id)arg1;
- (void)onPrivacyCellClicked; //谁能看
- (void)onQZoneClicked:(id)arg1;
- (void)onTwitterClicked:(id)arg1;
- (void)onWCPostPrivacyChanged;
- (void)onWithContactCellClicked;//提醒谁看
- (id)openOldText;

- (_Bool)processImage;
- (void)reloadData;
- (void)removeOldText;
- (void)restoreLastShareOptions;
- (void)saveShareOptions;

- (void)shareOptionsCheck;
- (_Bool)shouldJustReturnMMAsset;
- (_Bool)showAddView;
- (void)showPrivacyAlertView;
- (void)twitterAuthFinished:(int)arg1;
- (void)twitterCheckAccessTokenValidFinished:(int)arg1;
- (void)twitterWillStartOpenSafari;
- (void)updateImageLocation:(unsigned int *)arg1;
- (void)updateSelectorView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)writeOldText:(id)arg1;

    
@end

