//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface ChatRoomListViewController : UIViewController


- (void)JumpToChatRoom:(id)arg1;
- (void)commitEditingStyle:(long long)arg1 ForIndexPath:(id)arg2;
- (void)dealloc;
- (void)deleteContact:(id)arg1;
- (void)didSelectRowAtIndexPath:(id)arg1;
- (long long)getEditingStyleForIndexPath:(id)arg1;
- (_Bool)hasIndexBar;
- (id)init;
- (void)onContactListUpdate:(unsigned int)arg1;
- (void)onDeleteContact:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)showContactInfoView:(id)arg1;
- (void)updateCount;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;


@end

