//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface LbsContactInfoList : NSObject


- (void)addToLbsContactList:(id)arg1;
- (unsigned long long)countOfLbsContactList;
- (id)description;
- (_Bool)fromSKBuffer:(struct SKBuffer *)arg1;
- (void)getLbsContactList:(id *)arg1 range:(struct _NSRange)arg2;
- (void)insertLbsContactList:(id)arg1 atIndexes:(id)arg2;
- (void)insertObject:(id)arg1 inLbsContactListAtIndex:(unsigned long long)arg2;
- (id)keyPaths;
- (id)objectInLbsContactListAtIndex:(unsigned long long)arg1;
- (void)removeFromLbsContactList:(id)arg1;
- (void)removeLbsContactListAtIndexes:(id)arg1;
- (void)removeObjectFromLbsContactListAtIndex:(unsigned long long)arg1;
- (void)replaceLbsContactListAtIndexes:(id)arg1 withLbsContactList:(id)arg2;
- (void)replaceObjectInLbsContactListAtIndex:(unsigned long long)arg1 withObject:(id)arg2;

@end

