//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface MMTableViewCellInfo : NSObject


+ (id)centerCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 isFitIpadClassic:(_Bool)arg4;
+ (id)urlInnerBlueCellForTitle:(id)arg1 rightValue:(id)arg2 url:(id)arg3;
+ (id)urlInnerBlueCellForTitle:(id)arg1 leftValue:(id)arg2 url:(id)arg3 isFitIpadClassic:(_Bool)arg4;
+ (id)urlCellForTitle:(id)arg1 url:(id)arg2 isFitIpadClassic:(_Bool)arg3;
+ (id)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4 rightValue:(id)arg5 imageName:(id)arg6 isFitIpadClassic:(_Bool)arg7;
+ (id)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4 rightValue:(id)arg5 isFitIpadClassic:(_Bool)arg6;
+ (id)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4 isFitIpadClassic:(_Bool)arg5;
+ (id)normalCellForTitle:(id)arg1 rightValue:(id)arg2 imageName:(id)arg3 isFitIpadClassic:(_Bool)arg4;
+ (id)normalCellForTitle:(id)arg1 rightValue:(id)arg2 isFitIpadClassic:(_Bool)arg3;
+ (id)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 rightValue:(id)arg4 imageName:(id)arg5 accessoryType:(long long)arg6 isFitIpadClassic:(_Bool)arg7;
+ (id)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 rightValue:(id)arg4 accessoryType:(long long)arg5 isFitIpadClassic:(_Bool)arg6;
+ (id)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 accessoryType:(long long)arg4 isFitIpadClassic:(_Bool)arg5;
+ (id)editorCellForSel:(SEL)arg1 target:(id)arg2 tip:(id)arg3 focus:(_Bool)arg4 autoCorrect:(_Bool)arg5 text:(id)arg6 isFitIpadClassic:(_Bool)arg7;
+ (id)editorCellForSel:(SEL)arg1 target:(id)arg2 tip:(id)arg3 focus:(_Bool)arg4 text:(id)arg5 isFitIpadClassic:(_Bool)arg6;
+ (id)editorCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 margin:(double)arg4 tip:(id)arg5 focus:(_Bool)arg6 text:(id)arg7 isFitIpadClassic:(_Bool)arg8;
+ (id)editorCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 margin:(double)arg4 tip:(id)arg5 focus:(_Bool)arg6 autoCorrect:(_Bool)arg7 text:(id)arg8 isFitIpadClassic:(_Bool)arg9;
+ (id)switchCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 on:(_Bool)arg4 isFitIpadClassic:(_Bool)arg5;
+ (void)fitIpadClassic:(id)arg1;
+ (double)getAutoSizingRightMargin:(id)arg1;
+ (double)getRightMargin:(id)arg1;
+ (id)centerCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3;
+ (id)urlInnerBlueCellForTitle:(id)arg1 leftValue:(id)arg2 url:(id)arg3;
+ (id)urlInnerCellForTitle:(id)arg1 leftValue:(id)arg2 url:(id)arg3;
+ (id)urlCellForTitle:(id)arg1 url:(id)arg2;
+ (id)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4 rightValue:(id)arg5 imageName:(id)arg6;
+ (id)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4 rightValue:(id)arg5;
+ (id)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4;
+ (id)editorCellForSel:(SEL)arg1 target:(id)arg2 tip:(id)arg3 focus:(_Bool)arg4 text:(id)arg5;
+ (id)editorCellForSel:(SEL)arg1 target:(id)arg2 tip:(id)arg3 focus:(_Bool)arg4 autoCorrect:(_Bool)arg5 text:(id)arg6;
+ (id)editorCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 margin:(double)arg4 tip:(id)arg5 focus:(_Bool)arg6 text:(id)arg7;
+ (id)editorCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 margin:(double)arg4 tip:(id)arg5 focus:(_Bool)arg6 autoCorrect:(_Bool)arg7 text:(id)arg8;
+ (id)normalCellForTitle:(id)arg1 rightValue:(id)arg2 imageName:(id)arg3;
+ (id)normalCellForTitle:(id)arg1 rightValue:(id)arg2;
+ (id)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 accessoryType:(long long)arg4;
+ (id)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 rightValue:(id)arg4 imageName:(id)arg5 accessoryType:(long long)arg6;
+ (id)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 rightValue:(id)arg4 accessoryType:(long long)arg5;
+ (id)switchCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 on:(_Bool)arg4;
+ (id)cellForMakeSel:(SEL)arg1 makeTarget:(id)arg2 height:(double)arg3 userInfo:(id)arg4;
+ (id)cellForMakeSel:(SEL)arg1 makeTarget:(id)arg2 actionSel:(SEL)arg3 actionTarget:(id)arg4 calHeightSel:(SEL)arg5 calHeightTarget:(id)arg6 userInfo:(id)arg7;
+ (id)cellForMakeSel:(SEL)arg1 makeTarget:(id)arg2 actionSel:(SEL)arg3 actionTarget:(id)arg4 height:(double)arg5 userInfo:(id)arg6;
+ (id)cellForMakeSel:(SEL)arg1 makeTarget:(id)arg2 actionSel:(SEL)arg3 actionTarget:(id)arg4 height:(double)arg5 userInfo:(id)arg6 isFitIpadClassic:(_Bool)arg7;


- (void)makeEditorCell:(id)arg1;
- (void)makeCenterCell:(id)arg1;
- (void)makeNormalCell:(id)arg1;
- (void)makeNormalCell:(id)arg1 title:(id)arg2;
- (void)makeSwitchCell:(id)arg1;
- (void)actionUrlInnerCell;
- (void)actionUrlCell;
- (void)actionSwitchCell:(id)arg1;
- (void)actionEditorCell:(id)arg1;
- (id)init;

@end

