//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SeePeopleNearbyViewController : UIViewController


- (void)AddNewActionSheetCell2Array:(id)arg1 WithText:(id)arg2 WithImage:(id)arg3;
- (void)SettingMyAccountExtInfoExit;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 didSelectWithItem:(id)arg2;
- (void)adjustSubviewRects;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)bindPhoneReturn;
- (void)confirmClearMyLbsData:(id)arg1;
- (void)dealloc;
- (id)getSexImage;
- (void)goBackToRootView;
- (id)init;
- (_Bool)isProfileExtInfoOK;
- (void)onBindPhoneBtnClicked;
- (void)onBindQQBtnClicked;
- (void)onChatRoomNearByBtnClicked;
- (void)onClearMyLbsData;
- (void)onClearMyLbsDataFinishedWithResult:(_Bool)arg1;
- (void)onClickNeverPromptForAgree:(id)arg1;
- (void)onClickTipsBtn:(unsigned long long)arg1;
- (void)onGetCertificationFinish;
- (void)onGetLBSRecommendPoiList:(id)arg1;
- (void)onJoinChatRoomFailed;
- (void)onJoinChatRoomFinishedWithResult:(id)arg1;
- (void)onJoinChatRoomStart;
- (void)onRefreshMyFriends;
- (void)onSelectedWithLbsContactInfo:(id)arg1;
- (void)onSelectedWithLbsPoiItem:(id)arg1;
- (void)onUpdateLbsContactInfoError:(int)arg1;
- (void)onUpdateLbsContactInfoFinishedWithData:(id)arg1;
- (void)onUploadAddressbookBtnClicked;
- (void)promptForLBSUsageWarnning;
- (void)promptForProfileExtInfo;
- (void)setRightNavBtn;
- (void)setRightNavBtnNil;
- (void)setTitleNavView;
- (void)showContactInfoView:(id)arg1;
- (void)showMessage:(id)arg1;
- (void)showOperationMenu:(id)arg1;
- (void)showPeopleInfoView:(id)arg1;
- (void)startLoading;
- (void)startLoadingWithText:(id)arg1;
- (void)stopLoading;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willAppear;

@end

