//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SettingGeneralViewController : UIViewController

- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertNoAlbumAcess;
- (void)clearLocalData;
- (void)doSetPrivateConfig:(unsigned int)arg1 on:(_Bool)arg2 bitset:(unsigned int)arg3;
- (void)handelEmoticonSetting;
- (void)handleChatMigration;
- (void)handleFontSizeChange;
- (void)handleLanguageChange;
- (void)handleMMRestore;
- (void)initDeepLinkConfig;
- (void)onClearData;
- (void)onLoudModeSwitch:(id)arg1;
- (void)onNearModeSwitchChanged:(id)arg1;
- (void)onSetAutoDownloadSight;
- (void)onShakeToSightSwitch:(id)arg1;
- (void)onUploadHDImageSwitchChanged:(id)arg1;
- (void)onVoipRingToneSwitchChanged:(id)arg1;
- (void)reloadTableData;
- (void)showChatBackgroundConfig;
- (void)showClearLocalDataActionSheet:(id)arg1;
- (void)showNotificationView;
- (void)showPluginsView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;


@end

