//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface ShakeSingleView : UIView

- (void)doShowAnimation;
- (void)finishShowAnimation;
- (id)initWithItem:(id)arg1 andScene:(unsigned int)arg2;
- (_Bool)isClickHead:(struct CGPoint)arg1;
- (_Bool)isInMyContactList:(id)arg1;
- (_Bool)isPointInView:(struct CGPoint)arg1;
- (void)setM_Delegate:(id)arg1;
- (void)stopAllAnimation;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

