//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SharePreConfirmView : UIWindow


- (void)MMGrowTextViewBeginEditing:(id)arg1;
- (void)MMGrowTextViewHeightDidChanged:(id)arg1;
- (void)addBlurView:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)becomeInput;
- (void)dealloc;
@property(retain, nonatomic) NSString *defaultInputText; // @synthesize defaultInputText=_defaultInputText;
@property(retain, nonatomic) NSString *defaultShowText; // @synthesize defaultShowText=_defaultShowText;
- (void)didCommitEmptyText;
- (void)didCommitText:(id)arg1;
- (void)formCardContentView:(id)arg1;
- (void)formContentViewByText:(id)arg1;
- (void)formContentViewByText:(id)arg1 lineNum:(long long)arg2;
- (void)formEmoticonContentView:(id)arg1;
- (void)formImageContentView:(id)arg1;
- (void)formLinkContentView:(id)arg1;
- (void)formLocationMsgContentView:(id)arg1;
- (void)formMultiMsgContentView;
- (void)formNoteContentView:(id)arg1;
- (void)formRecordMsgContentView:(id)arg1;
- (void)formTextMsgContentView:(id)arg1;
@property(retain, nonatomic) NSString *fromAppName; // @synthesize fromAppName=_fromAppName;
- (id)genBackgroundView;
- (id)genNewBigButton;
- (id)getBlurView;
- (id)getInputText;
- (double)getVisibleHeight;
- (id)getWebThumbImage;
@property(nonatomic) _Bool hasInputSth; // @synthesize hasInputSth=_hasInputSth;
- (void)hideKeyBoard;
- (void)hideView:(_Bool)arg1;
- (id)init;
- (void)initBottomButtons;
- (void)initChatroomProfileView:(id)arg1;
- (void)initContentView;
- (void)initEmoticonView;
- (void)initInputController;
- (void)initInputToolView;
- (void)initInputView;
- (void)initTitleView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)internalInit;
@property(nonatomic) _Bool isShowTextView; // @synthesize isShowTextView=_isShowTextView;
- (void)keyboardDidHide;
- (void)keyboardWillShow;
- (void)layoutSubviewToOrientation:(long long)arg1;
@property(retain, nonatomic) NSArray *m_arrMsgs; // @synthesize m_arrMsgs=_m_arrMsgs;
@property(retain, nonatomic) NSArray *m_arrToContacts; // @synthesize m_arrToContacts=_m_arrToContacts;
@property(retain, nonatomic) NSArray *m_msgRecordOriginList; // @synthesize m_msgRecordOriginList=_m_msgRecordOriginList;
- (void)notifySendMsgOK;
- (void)onCancel;
- (void)onConfirm;
- (void)onExpressionButtonClicked:(id)arg1;
- (void)onKickQuit;
- (void)onLoadImageOK:(id)arg1;
- (void)onMainWindowFrameChanged;
- (void)onPressBackBtn;
- (void)onTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)registerEvent;
- (void)reloadExpressionButtonImage:(int)arg1;
- (void)resignInput;
- (void)rotateToCurrentOrientation;
- (void)rotateToOrientation:(long long)arg1;
- (void)setHidden:(_Bool)arg1;
@property(nonatomic) unsigned long long singlePasteTextMaxLength; // @synthesize singlePasteTextMaxLength=_singlePasteTextMaxLength;
@property(retain, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSString *stayAtString; // @synthesize stayAtString=_stayAtString;
@property(retain, nonatomic) NSString *successText; // @synthesize successText=_successText;
@property(retain, nonatomic) UIImage *thumbImage; // @synthesize thumbImage=_thumbImage;
@property(retain, nonatomic) NSString *thumbImageUrl; // @synthesize thumbImageUrl=_thumbImageUrl;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)showSendSuccessView;
- (void)showView:(_Bool)arg1;
- (void)stayAtWeChat;
- (void)textViewTextDidChange;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)unregisterEvent;
- (void)viewChatroomProfile:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

