//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WCActionSheet : UIWindow

+ (long long)getActionSheetWidth;

- (void)OnCancel:(id)arg1;
- (void)OnDefaultButtonTapped:(id)arg1;
- (long long)addButtonWithTitle:(id)arg1;
- (void)addTapRecognizer;

- (id)buttonTitleAtIndex:(long long)arg1;

- (void)deviceDidRotate:(id)arg1;
- (void)dismissWithClickedButtonIndex:(long long)arg1 animated:(_Bool)arg2;

- (id)genGrayBarView;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;

- (double)heightOfWholeSheet;
- (id)init;
- (id)initWithTitle:(id)arg1 delegate:(id)arg2 cancelButtonTitle:(id)arg3 destructiveButtonTitle:(id)arg4 otherButtonTitles:(id)arg5;

- (id)makePannelViewWithButtonList:(id)arg1 withCancelButtonTitle:(id)arg2;
- (id)makeTitleViewWithTitle:(id)arg1;

- (void)onOpenApiWillBeginShare:(id)arg1;
- (void)onStatusBarFrameChanged;

- (void)reloadInnerView:(id)arg1;
- (void)setCancelButtonTextColor:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;

- (void)shouldHideOnRotate;
- (void)showInView:(id)arg1;
- (void)tapOut:(id)arg1;






@end

