//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WCListViewController : UIViewController

- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)forceReload;
- (void)initBarItem;
- (void)initData:(BOOL)arg1;
- (void)onDissmiss;
- (void)onHomepageUpdate:(int)arg1 withAdded:(id)arg2 andChanged:(id)arg3 andDeleted:(id)arg4;
- (void)onNetworkActivityStatusChanged;
- (void)onOperate:(id)arg1;
- (void)refreshFooter;
- (void)refreshHeader;
- (void)reloadData;
- (void)reloadStyle;
- (void)updateNetworkStatus;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)willAppear;
- (void)willDisappear;
- (void)willDisshow;
- (void)willShow;


- (void)stopLoading;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldEnableKeyboardInteractivePop;
- (_Bool)shouldInteractivePop;
- (_Bool)shouldOtherPreventedAutorotateToInterfaceOrientation;

@end

