//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface CBaseContact : NSObject

- (id)chatRoomTopic;
- (long long)compare:(id)arg1;
- (_Bool)copyFrom:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)getContactDisplayName;
- (id)getContactDisplayUsrName;
- (id)getContactHeadImage;
- (id)getContactTalkRoomName;
- (id)getEncodeUserName;
- (int)getImageStatusCode;
- (id)getQQDisplayName;
- (id)getRemark;
- (id)getValueTypeTable;
- (_Bool)hasContactDisplayUsrName;
- (_Bool)hasContactDisplayUsrNameByCache;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (_Bool)isBlack;
- (_Bool)isBrandSessionHolder;
- (_Bool)isChatRoomContact;
- (_Bool)isChatStatusNotifyOpen;
- (_Bool)isChatroom;
- (_Bool)isEnterpriseContact;
- (_Bool)isEqualToContact:(id)arg1;
- (_Bool)isEqualToName:(id)arg1;
- (_Bool)isFavour;
- (_Bool)isFileHelper;
- (_Bool)isGroupCard;
- (_Bool)isHasGMail;
- (_Bool)isHasHDImg;
- (_Bool)isHasQQ;
- (_Bool)isHasQQDisplayName;
- (_Bool)isLbsroom;
- (_Bool)isMMContact;
- (_Bool)isNeedGetHDImg;
- (_Bool)isNeedGetUsrImg;
- (_Bool)isNeedGetUsrImgWithoutCheckLocalFile;
- (_Bool)isQQ;
- (_Bool)isQQMBlog;
- (_Bool)isSelf;
- (_Bool)isSnsBlack;
- (_Bool)isTemplateMsgHolder;
- (_Bool)isValid;
- (_Bool)isWeixin;
- (_Bool)isWeixinTeamContact;
- (id)localizedStringForMale:(id)arg1 female:(id)arg2 andUnkownSex:(id)arg3;
- (void)saveUserImage;
- (void)setBlack:(_Bool)arg1;
- (void)setChatRoomTopic:(id)arg1;
- (void)setNickNameWithoutEmojiChange:(id)arg1;
- (void)setRemarkWithoutEmojiChange:(id)arg1;
- (void)setSnsBlack:(_Bool)arg1;
@end

