//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface CSetting : NSObject


- (id)description;
- (id)getDicSetting;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)keyPaths;
- (void)preInit;
- (void)setBool:(_Bool)arg1 forKey:(id)arg2;
- (void)setInt32:(int)arg1 forKey:(id)arg2;
- (void)setUInt32:(unsigned int)arg1 forKey:(id)arg2;
- (id)theadSafeGetObject:(id)arg1;
- (void)theadSafeRemoveObjectForKey:(id)arg1;
- (void)theadSafeSetObject:(id)arg1 forKey:(id)arg2;

@end

