//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface WCAccountLoginControlLogic : NSObject

- (void)onFirstUserLoginUserName:(id)arg1 Pwd:(id)arg2;
- (void)onLastUserLoginUserName:(id)arg1 Pwd:(id)arg2;

@end

