//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface FindFriendEntryViewController : UIViewController

- (void)BottlePluginChanged:(_Bool)arg1;
- (void)BottleTotalUnreadCountChanged;
- (void)OnShakeVCDealloc;
- (void)OpenSandyBeach;
- (void)SettingMyAccountExtInfoExit;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)checkDBAutoRecover;
- (void)checkIfAnimationFail;
- (void)clickEntryBtn:(id)arg1;
- (void)closeAlbum;
- (int)convertGameNotifyTypeToFirstDisplayStatFlag:(unsigned long long)arg1;
- (int)convertGameNotifyTypeToStatFlag:(unsigned long long)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)doSelectCell:(long long)arg1;
- (unsigned int)getBottleUnreadCountAtCell;
- (unsigned int)getBottleUnreadCountAtTarbar;
- (long long)getCurrentTotalCount;
- (id)getVCWithDeepLinkName:(id)arg1;
- (void)goToSandyBeach;
- (void)goToShakeWithAnimate:(_Bool)arg1;
- (void)handleGameCenterLongPress:(id)arg1;
- (void)handleJDStoreCell:(id)arg1;
- (void)handleSelectedEntryCell:(unsigned long long)arg1;
- (id)init;
- (void)initDeepLinkConfig;
- (void)initRow;
- (void)initTableView;
- (void)initTitle;
- (void)initView;
- (void)layoutGameCell:(id)arg1 rowType:(unsigned long long)arg2;
- (void)makeEntryCell:(id)arg1 rowType:(unsigned long long)arg2;
- (void)makeJDStoreEntryCell:(id)arg1;
- (void)markGameCenterEntryRead;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onCloseAlbumTimeOut;
- (void)onDatabaseReloaded;
- (void)onDidFetchedContent:(id)arg1;
- (void)onDidFetchedNoContentWithError:(unsigned long long)arg1;
- (void)onDiskStorageWarningCleanedSize:(unsigned int *)arg1;
- (void)onFontSizeChange;
- (void)onFriendAssistUnreadCountChanged;
- (void)onGameEntryChanged;
- (void)onGameGiftInfoChanged;
- (void)onGameMessageUnReadCountChanged;
- (void)onGameNewAppCountChanged;
- (void)onHomepageUpdate:(int)arg1 withAdded:(id)arg2 andChanged:(id)arg3 andDeleted:(id)arg4;
- (void)onJdBussinessEntranceChanged;
- (void)onLatestWCObjectChanged:(id)arg1;
- (void)onMMDynamicConfigUpdated;
- (void)onMarkTimelineListReadWithTid:(id)arg1 andCreateTime:(unsigned long long)arg2;
- (void)onMarkWCObjectAsRead:(id)arg1;
- (void)onMessageUnReadCountChanged;
- (void)onNewGameAdChanged;
- (void)onNotificationShowSettingChanged;
- (void)onReveiceWCMessage:(id)arg1;
- (void)onSettingExtChanged:(int)arg1;
- (void)onShakeCardRedDotChange;
- (void)onShakeMsgUnreadCountChanged;
- (void)onShakeStatusChanged;
- (void)onTimeLineViewReturn;
- (void)openAlbum;
- (void)openAlbumAnimated:(_Bool)arg1;
- (void)openCameraScan:(int)arg1;
- (void)openFloatBottle;
- (void)openGameCenter;
- (void)openLBS;
- (void)openNormalShake;
- (void)openShakeFromInnerWithAnimate:(_Bool)arg1;
- (void)openShakeWithAnimate:(_Bool)arg1;
- (void)pluginsChanged:(id)arg1;
- (id)preOpenAlbumView;
- (void)promptForProfileExtInfo;
- (void)reloadData;
- (void)reloadGameRow;
- (void)resetRowType;
- (void)resetSectionType;
- (void)selectGameCenterVersion;
- (void)statGameEntryNotifyDisplay:(unsigned long long)arg1 withAdInfo:(id)arg2;
- (void)statGameEntryNotifyDisplay:(unsigned long long)arg1 withGiftInfo:(id)arg2;
- (void)statGameEntryNotifyDisplay:(unsigned long long)arg1 withMessage:(id)arg2;
- (void)statViewOrClickJDCell:(unsigned int)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tryInit;
- (void)trySetDefaultHeadImage;
- (void)updateBottleEntryRow;
- (void)updateTabBarBadge;
- (void)updateViewWhenSelectTab:(_Bool)arg1;
- (void)updateWCTimeLineView:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willAppear;


@end

