//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface WCAccountLoginControlLogic : UIViewController

- (_Bool)onHandleError:(id)arg1;


- (void)OnLoginVerifyOverLimit;
- (void)OnLoginVerifySucessWithRandomAuthKey:(id)arg1 andTicket:(id)arg2;
- (void)checkStopLogic;
- (id)getArchive;
- (void)loginAccount:(_Bool)arg1;
- (void)onFacebookConnect;
- (void)onFirstUserBack;
- (void)onFirstUserLoginUserName:(id)arg1 Pwd:(id)arg2;
- (void)onFirstUserProblem:(id)arg1;
- (void)onFirstViewLogin;
- (void)onFirstViewRegester;
- (void)onGoToSecurityCenter:(unsigned int)arg1;
- (void)onIpadOneKeyLoginByQQ;
- (void)onLastUserChangeAccount:(id)arg1;
- (void)onLastUserChangeAccountWithView:(id)arg1;
- (void)onLastUserGoToSecurityCenter:(id)arg1;
- (void)onLastUserLoginByQRCode;
- (void)onLastUserLoginFromePhone:(id)arg1;
- (void)onLastUserLoginUserName:(id)arg1 Pwd:(id)arg2;
- (void)onLastUserProblem:(id)arg1;
- (void)onLastUserRegister;
- (void)onLastUserVoicePrintLogin:(id)arg1;
- (void)onLoginByPhone;
- (void)onLoginByPhoneFromQQ;
- (void)onLoginByQQ;
- (void)onLoginByQRCode;
- (void)onLoginByQRCodeWithOneClickDisconnect;
- (_Bool)onManualAuthControlLogicError:(id)arg1;
- (void)onManualAuthControlLogicStop:(unsigned long long)arg1 response:(id)arg2;
- (void)onUseBothDevice;
- (void)onUseIPadOnly;
- (void)onWCBaseLogicDidStop:(unsigned int)arg1;
- (void)pause;
- (_Bool)recoverFromArchive:(id)arg1;
- (void)resetPwdByPhone;
- (void)resetPwdByQQ;
- (id)setRootviewController:(Class)arg1 withData:(id)arg2;
- (id)setRootviewController:(Class)arg1 withData:(id)arg2 shouldHideNavBar:(_Bool)arg3;
- (void)startIPadLoginLogic;
- (void)startIPhoneLoginLogic;
- (void)startLogic;
- (void)stopLogic;

@end

