//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface CAppViewControllerManager : NSObject


+ (id)getAppViewControllerManager;

- (id) getMainWindow;
- (id) getTabBarController;
- (id) getNewMainFrameViewController;
- (void)dismissToRootViewController;

- (void)jumpToAlbum;
- (id)getTabBarBaseViewController:(unsigned long long)arg1;

@end

