//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SelectAttachmentViewController : UIViewController

@property(nonatomic) _Bool allowEnterpriseBrandEntry; // @synthesize allowEnterpriseBrandEntry=_allowEnterpriseBrandEntry;
@property(nonatomic) _Bool allowMultiTalk; // @synthesize allowMultiTalk;
@property(nonatomic) _Bool allowNameCardFollowRedEnvelope; // @synthesize allowNameCardFollowRedEnvelope=_allowNameCardFollowRedEnvelope;
@property(nonatomic) _Bool allowWXTalkFollowSight; // @synthesize allowWXTalkFollowSight=_allowWXTalkFollowSight;
@property(nonatomic) _Bool allowShareCard; // @synthesize allowShareCard=_allowShareCard;
@property(nonatomic) _Bool allowRecommendApp; // @synthesize allowRecommendApp=_allowRecommendApp;
@property(nonatomic) _Bool allowWxTalk; // @synthesize allowWxTalk=_allowWxTalk;
@property(nonatomic) _Bool allowVoiceInput; // @synthesize allowVoiceInput=_allowVoiceInput;
@property(nonatomic) _Bool allowVoiceVoip; // @synthesize allowVoiceVoip=_allowVoiceVoip;
@property(nonatomic) _Bool allowVideoVoip; // @synthesize allowVideoVoip=_allowVideoVoip;
@property(nonatomic) _Bool allowFavEntry; // @synthesize allowFavEntry=_allowFavEntry;
@property(nonatomic) _Bool allowUploadLocation; // @synthesize allowUploadLocation=_allowUploadLocation;
@property(retain, nonatomic) NSArray *m_svcApps; // @synthesize m_svcApps;
@property(retain, nonatomic) NSArray *m_rcmApps; // @synthesize m_rcmApps;


- (void)setSelectAttachmentViewAccessibility:(_Bool)arg1;
- (void)adjustViewAndNavBarRect;
- (void)onTopBarFrameChanged;
- (void)OnAppSettingChanged;
- (void)OnNewAppStatusChanged;
- (void)OnAppIconChanged:(id)arg1;
- (void)OnAppRegisterInfoChanged;
- (void)MMTransparentButton_touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)MMTransparentButton_touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)descriptionForAttachmentAtIndex:(unsigned int)arg1;
- (id)viewForAttachmentAtIndex:(unsigned int)arg1;
- (void)OnAttachmentClicked:(id)arg1;
- (unsigned long long)numberOfCols;
- (unsigned long long)numberOfRows;
- (unsigned long long)numberOfAttachment;
- (id)getTextAtIndex:(unsigned int)arg1;
- (id)getImageAtIndex:(unsigned int)arg1;
- (id)appIDAtIndex:(unsigned int)arg1;
- (void)viewDidLoad;
- (void)resetView;
- (void)updateView;
- (void)dealloc;
- (id)init;
- (void)initObjectItem;
- (void)initData;




@end

