//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface YKCVipModel : NSObject

@property(copy, nonatomic) NSURL  *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSNumber  *mmid; // @synthesize mmid=_mmid;
@property(copy, nonatomic) NSString  *name; // @synthesize name=_name;
@property(copy, nonatomic) NSNumber  *state; // @synthesize state=_state;
@property(copy, nonatomic) NSNumber  *vipGrade; // @synthesize vipGrade=_vipGrade;

@end

