//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface ShakeSingleView : UIView
{
    ShakeGetItem *m_oShakeGetItem;
}
- (id)initWithItem:(id)arg1 andScene:(unsigned int)arg2;

@end

